inherit_from: https://raw.githubusercontent.com/fmi/ruby-homework/master/.rubocop.yml

AllCops:
  DisabledByDefault: true

Metrics/LineLength:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Enabled: true
  Max: 10

Metrics/BlockNesting:
  Enabled: true
  Max: 3

Metrics/ParameterLists:
  Enabled: true
  Max: 4
